### PR TITLE
Spelling fixes in various sections.

### PR DESCRIPTION
**Pull request by GaPhil**
This PR aims to fix some odd formulations, whilst maintaining the intended meaning of the sentences.

### CODE REVIEW

**Comment by GaPhil** [comment]
There are similar fixes that could be added to `master`.

**Comment by raphaelrobert** [comment]
👍

Let me know when you're done and I'll review and merge

**Comment by GaPhil** [comment]
@raphaelrobert See https://github.com/mlswg/mls-federation/pull/4 for the `master` PR.

**Comment by raphaelrobert** [comment]
Closing this since the document will be reworked completely.

**Pull request closed without merging**
